server:
  port: 8081

spring:
  application:
    name: ClientApplication

eureka:
  client:
    register-with-eurika: true
    fetch-registry: true
    service-url:
      defualtZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost